In [1]:
import tkinter as tk
from tkinter import ttk
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [2]:
#  Correct Dataset Path
csv_filename = r"D:/Projects/all_fraud_detection/notebook/upi_combined_dataset.csv"

In [3]:
#  Check if dataset exists
if not os.path.exists(csv_filename):
    print(f" Dataset not found at: {csv_filename}")
    exit()

In [4]:
#  Load Dataset
try:
    df_raw = pd.read_csv(csv_filename)
    print(" Dataset loaded successfully!")
except Exception as e:
    print(f" Failed to read dataset: {e}")
    exit()

 Dataset loaded successfully!


In [5]:
#  Prepare Data & Train Model
df = df_raw.copy()
X = df.drop(['sequence_no', 'transaction_id', 'label'], axis=1)
y = df['label'].map({'not fraud': 0, 'fraud': 1})

label_encoders = {}
for col in ['sender_name', 'receiver_name', 'transaction_app', 'date', 'time']:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    label_encoders[col] = le

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier()
model.fit(X_train, y_train)

print(" Model trained successfully!")

 Model trained successfully!


In [6]:
#  Prediction Function
def predict_fraud(seq_no):
    try:
        seq_no = int(seq_no)
        row = df_raw[df_raw['sequence_no'] == seq_no]
        if row.empty:
            result_var.set("Sequence No. not found.")
            print(" Invalid Sequence Number")
            return

        # Fill GUI fields
        row_data = row.iloc[0]
        for i, var in enumerate(field_vars):
            var.set(row_data[columns[i]])

        print("🔍 Raw selected row:")
        print(row_data)
        # Prepare input
        input_data = row.drop(['sequence_no', 'transaction_id', 'label'], axis=1).copy()
        for col in ['sender_name', 'receiver_name', 'transaction_app', 'date', 'time']:
            input_data[col] = label_encoders[col].transform([input_data[col]])[0]

        print(" Encoded input to model:")
        print(input_data.values)

        # Prediction
        prediction = model.predict(input_data.values.reshape(1, -1))[0]
        result = " Fraud Detected" if prediction == 1 else "✅ Transaction is Safe"
        print(" Prediction result:", result)

        result_var.set(result)

    except Exception as e:
        result_var.set(f" Error: {e}")
        print(" Exception occurred:", e)

In [7]:
#  GUI Setup
root = tk.Tk()
root.title("UPI Fraud Detection System")
root.geometry("460x660")
root.configure(bg="white")

tk.Label(root, text="Enter Sequence Number:", bg="white", font=('Arial', 12)).pack(pady=10)
seq_var = tk.StringVar()
ttk.Entry(root, textvariable=seq_var).pack(pady=5)

tk.Button(root, text="Load & Predict", command=lambda: predict_fraud(seq_var.get()), width=20).pack(pady=15)

columns = ['transaction_id', 'sender_name', 'receiver_name', 'amount', 'date', 'time', 'transaction_app']
field_vars = [tk.StringVar() for _ in columns]

for label, var in zip(columns, field_vars):
    tk.Label(root, text=label.replace('_', ' ').title() + ":", bg="white", anchor='w', font=('Arial', 10)).pack(fill='x', padx=20)
    tk.Entry(root, textvariable=var, state='readonly', bg="#f0f0f0", font=('Arial', 10)).pack(fill='x', padx=20, pady=2)

result_var = tk.StringVar()
tk.Label(root, text="Prediction Result:", bg="white", font=('Arial', 14)).pack(pady=10)
tk.Label(root, textvariable=result_var, bg="white", font=('Arial', 16, 'bold'), fg="green").pack(pady=5)

root.mainloop()

🔍 Raw selected row:
sequence_no                16
transaction_id        TNX1016
sender_name             Frank
receiver_name             Bob
amount                   8700
date               2025-07-08
time                 19:00:00
transaction_app          BHIM
label                   fraud
Name: 15, dtype: object
 Encoded input to model:
[[   5    1 8700    8   19    0]]
 Prediction result:  Fraud Detected


c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData

 Invalid Sequence Number
🔍 Raw selected row:
sequence_no                22
transaction_id        TNX1022
sender_name             Frank
receiver_name            Dave
amount                   9400
date               2025-07-11
time                 22:20:00
transaction_app       PhonePe
label                   fraud
Name: 21, dtype: object
 Encoded input to model:
[[   5    3 9400   11   22    3]]
 Prediction result:  Fraud Detected


c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData

🔍 Raw selected row:
sequence_no                23
transaction_id        TNX1023
sender_name               Bob
receiver_name             Eve
amount                   1300
date               2025-07-12
time                 12:10:00
transaction_app         Paytm
label               not fraud
Name: 22, dtype: object
 Encoded input to model:
[[   1    4 1300   12    9    2]]
 Prediction result: ✅ Transaction is Safe


c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Sayal\AppData

In [8]:
import joblib  # ← ensure this is present

# Save the trained model
joblib.dump(model, "upi_fraud_model.pkl")
print(" Model saved to 'upi_fraud_model.pkl'")

 Model saved to 'upi_fraud_model.pkl'
